BUG fix lazy inverse computation
esheldon/esutil pull request #69
Opened 2021-10-30 02:00 UTC by beckermr

This PR fixes a bug where upon read the lazy inverse was being marked as computed even if it was not. 

closes #68

2021-10-30 02:01 UTC, beckermr commented
cc @esheldon for review!

2021-10-30 10:04 UTC, esheldon requested changes
looks good to me, but I'm curious what @erykoff thinks

2021-10-30 10:04 UTC, esheldon commented on esutil/wcsutil.py
> +                # If inverse can't be found, make sure we computed it later
probably should be "make sure we compute it later"

2021-10-30 10:19 UTC, beckermr commented on esutil/wcsutil.py
> +                # If inverse can't be found, make sure we computed it later
```suggestion
                # If inverse can't be found, make sure we compute it later
```

2021-11-01 15:46 UTC, erykoff commented
I'm trying to follow what triggers this and what's the manifestation of the bug...

2021-11-01 15:48 UTC, beckermr commented
Just plug any DECam finalcut image into the WCS class and try to get the inverse with find=False.

2021-11-01 15:49 UTC, beckermr commented
The manifestation is that the output coordinates in x,y are manifestly incorrect. It always returns crpix!

2021-11-01 15:50 UTC, erykoff commented
And with this change it will `Raise` instead?

2021-11-01 15:51 UTC, beckermr commented
Nope. It correctly computes the inverse lazily and returns the right coordinates.

2021-11-01 15:53 UTC, erykoff commented
Then I clearly completely misunderstood the original code.  So this is fine.

2021-11-01 15:55 UTC, esheldon approved these changes

2021-11-01 15:55 UTC, merged